require "rake/testtask"
require "rake/clean"
require "rake/rdoctask"
require "rake/gempackagetask"

PROJECT_VERSION = '0.1'

# Ruby library code.
LIB_FILES = FileList["lib/**/*.rb"]

# Options common to RDocTask AND Gem::Specification.
#   The --main argument specifies which file appears on the index.html page
GENERAL_RDOC_OPTS = {
  "--title" => "SNMP Agent for Ruby"
}

# Output directory for the rdoc html files.
RDOC_HTML_DIR = "doc"

# Filelist with Test::Unit test cases.
TEST_FILES = FileList["test/**/*_test.rb"]

# Executables
BIN_FILES = FileList["bin/*"]

# Files included in distribution
DIST_FILES = FileList["**/*.rb", "**/*.rdoc"]
DIST_FILES.include("Rakefile", "TODO")
DIST_FILES.include(BIN_FILES)
# Don't package files which are autogenerated by RDocTask
DIST_FILES.exclude(/^(\.\/)?#{RDOC_HTML_DIR}(\/|$)/)

# Run the tests if rake is invoked without arguments.
task "default" => ["test"]

Rake::TestTask.new do |t|
  t.test_files = TEST_FILES
  t.libs = ["lib"]
end

GEM_SPEC = Gem::Specification.new do |s|
  s.name = 'snmp-agent'
  s.version = PROJECT_VERSION
  s.summary = 'A Ruby implementation of an SNMP agent'
  s.rubyforge_project = 'snmplib'
  s.homepage = "http://snmplib.rubyforge.org/"
  s.author = 'Matthew Palmer'
  s.email = 'mpalmer@hezmatt.org'
  s.files = DIST_FILES
  s.test_files = TEST_FILES
  s.executables = BIN_FILES.map { |fn| File.basename(fn) }
  s.has_rdoc = true
  s.rdoc_options = GENERAL_RDOC_OPTS.to_a.flatten
end

Rake::GemPackageTask.new(GEM_SPEC) do |pkg|
  pkg.need_zip = true
  pkg.need_tar = true
end

Rake::RDocTask.new("rdoc") do |t|
  t.rdoc_files = LIB_FILES
  t.title = GENERAL_RDOC_OPTS["--title"]
  t.main = GENERAL_RDOC_OPTS["--main"]
  t.rdoc_dir = RDOC_HTML_DIR
end
